"""
Barzel Analytics V3 — PDF Memo Generator
Uses ReportLab to produce a professional investment memo PDF.
"""

from fastapi import APIRouter
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from typing import List
import io

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib.colors import HexColor
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak,
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT

from services.kpi_engine import get_snapshot, get_snapshots_by_district, ALL_DISTRICTS
from services.barzel_score import compute_barzel_score, compute_barzel_scores_by_district

router = APIRouter()

# ─── Colors ──────────────────────────────────────────────────────────────────
NAVY    = HexColor("#0A1628")
GOLD    = HexColor("#C9A84C")
BLUE    = HexColor("#1E5FA8")
GREEN   = HexColor("#1A7A4A")
RED     = HexColor("#C0392B")
GREY_BG = HexColor("#F4F6F9")
BORDER  = HexColor("#D8E2EE")
WHITE   = HexColor("#FFFFFF")
TEXT_S  = HexColor("#3D5470")
TEXT_M  = HexColor("#7A90A8")


def _score_color(total: float):
    if total >= 65: return GREEN
    if total >= 40: return GOLD
    return RED


def _build_styles():
    ss = getSampleStyleSheet()
    ss.add(ParagraphStyle("MemoTitle", fontName="Helvetica-Bold", fontSize=22,
                          textColor=NAVY, spaceAfter=4, alignment=TA_LEFT))
    ss.add(ParagraphStyle("MemoSubtitle", fontName="Helvetica", fontSize=11,
                          textColor=TEXT_M, spaceAfter=12))
    ss.add(ParagraphStyle("SectionTitle", fontName="Helvetica-Bold", fontSize=14,
                          textColor=NAVY, spaceBefore=18, spaceAfter=8))
    ss.add(ParagraphStyle("BodyText2", fontName="Helvetica", fontSize=10,
                          textColor=TEXT_S, spaceAfter=6, leading=14))
    ss.add(ParagraphStyle("SmallGrey", fontName="Helvetica", fontSize=8,
                          textColor=TEXT_M, spaceAfter=4))
    ss.add(ParagraphStyle("KpiLabel", fontName="Helvetica", fontSize=8,
                          textColor=TEXT_M, alignment=TA_CENTER))
    ss.add(ParagraphStyle("KpiValue", fontName="Helvetica-Bold", fontSize=16,
                          textColor=NAVY, alignment=TA_CENTER))
    return ss


class PdfRequest(BaseModel):
    districts: List[str]
    language: str = "fr"


T = {
    "fr": {
        "title": "Barzel Investment Memo",
        "subtitle": "Analyse de marché · Dubai",
        "overview": "Vue d'ensemble",
        "comparison": "Comparaison des districts",
        "scoring": "Barzel Score",
        "metrics": ["Médiane AED/sqm", "DOM médian", "Fast-sale ≤60j", "Yield net", "Yield brut", "Service charge", "Nb annonces"],
        "disclaimer": "Ce document est généré automatiquement par Barzel Analytics V3. Il ne constitue pas un conseil en investissement.",
        "score_label": "Score",
        "district": "District",
    },
    "en": {
        "title": "Barzel Investment Memo",
        "subtitle": "Market Analysis · Dubai",
        "overview": "Overview",
        "comparison": "District Comparison",
        "scoring": "Barzel Score",
        "metrics": ["Median AED/sqm", "Median DOM", "Fast-sale ≤60d", "Net yield", "Gross yield", "Service charge", "Listings"],
        "disclaimer": "This document is auto-generated by Barzel Analytics V3. It does not constitute investment advice.",
        "score_label": "Score",
        "district": "District",
    },
}


def _fmt(val, suffix="", decimals=1):
    if val is None: return "—"
    if isinstance(val, float):
        return f"{val:,.{decimals}f}{suffix}"
    return f"{val:,}{suffix}"


@router.post("/generate")
async def generate_pdf(request: PdfRequest):
    lang = request.language if request.language in T else "fr"
    t = T[lang]
    districts = request.districts if request.districts else ALL_DISTRICTS

    # Fetch data
    snapshot = get_snapshot(districts)
    by_district = get_snapshots_by_district(districts)
    agg_score = compute_barzel_score(districts)
    dist_scores = compute_barzel_scores_by_district(districts)

    # Build PDF
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4,
                            leftMargin=20*mm, rightMargin=20*mm,
                            topMargin=25*mm, bottomMargin=20*mm)
    styles = _build_styles()
    elements = []

    # ── Header ──────────────────────────────────────────────────────────────
    elements.append(Paragraph(t["title"], styles["MemoTitle"]))
    elements.append(Paragraph(
        f'{t["subtitle"]} · {len(districts)} district{"s" if len(districts) > 1 else ""} · {snapshot.get("n_listings", 0):,} annonces',
        styles["MemoSubtitle"],
    ))
    # Gold line
    gold_line = Table([[""]], colWidths=[40*mm], rowHeights=[2])
    gold_line.setStyle(TableStyle([("BACKGROUND", (0,0), (-1,-1), GOLD)]))
    elements.append(gold_line)
    elements.append(Spacer(1, 12))

    # ── Overview KPIs ───────────────────────────────────────────────────────
    elements.append(Paragraph(t["overview"], styles["SectionTitle"]))

    kpi_data = [
        ("Median AED/sqm" if lang == "en" else "Médiane AED/sqm",
         _fmt(snapshot.get("median_price_sqm"), " AED", 0)),
        ("Median DOM" if lang == "en" else "DOM médian",
         _fmt(snapshot.get("median_dom"), "d", 0)),
        ("Net Yield" if lang == "en" else "Yield net",
         _fmt(snapshot.get("median_net_yield"), "%")),
        ("Barzel Score",
         _fmt(agg_score.get("total"), "/100")),
    ]

    kpi_table_data = [
        [Paragraph(v, styles["KpiValue"]) for _, v in kpi_data],
        [Paragraph(l, styles["KpiLabel"]) for l, _ in kpi_data],
    ]
    kpi_table = Table(kpi_table_data, colWidths=[doc.width/4]*4, rowHeights=[28, 16])
    kpi_table.setStyle(TableStyle([
        ("ALIGN", (0,0), (-1,-1), "CENTER"),
        ("VALIGN", (0,0), (-1,-1), "MIDDLE"),
        ("BOX", (0,0), (-1,-1), 0.5, BORDER),
        ("INNERGRID", (0,0), (-1,-1), 0.5, BORDER),
        ("BACKGROUND", (0,0), (-1,-1), WHITE),
        ("TOPPADDING", (0,0), (-1,0), 8),
        ("BOTTOMPADDING", (0,1), (-1,1), 6),
    ]))
    elements.append(kpi_table)
    elements.append(Spacer(1, 16))

    # ── Comparison table ────────────────────────────────────────────────────
    elements.append(Paragraph(t["comparison"], styles["SectionTitle"]))

    metric_keys = [
        ("median_price_sqm", 0, " AED"),
        ("median_dom", 0, "d"),
        ("fast_sale_60d_pct", 1, "%"),
        ("median_net_yield", 1, "%"),
        ("median_gross_yield", 1, "%"),
        ("median_service_charge", 0, " AED"),
        ("n_listings", 0, ""),
    ]

    header = [Paragraph(f'<b>{t["district"]}</b>', styles["SmallGrey"])]
    header += [Paragraph(f'<b>{m}</b>', styles["SmallGrey"]) for m in t["metrics"]]

    table_data = [header]
    for d in by_district:
        row = [Paragraph(f'<b>{d["district"]}</b>', styles["BodyText2"])]
        for key, dec, suf in metric_keys:
            row.append(Paragraph(_fmt(d.get(key), suf, dec), styles["BodyText2"]))
        table_data.append(row)

    n_cols = len(header)
    col_w = doc.width / n_cols
    comp_table = Table(table_data, colWidths=[col_w]*n_cols)
    comp_style = [
        ("ALIGN", (0,0), (-1,-1), "CENTER"),
        ("ALIGN", (0,0), (0,-1), "LEFT"),
        ("VALIGN", (0,0), (-1,-1), "MIDDLE"),
        ("FONTSIZE", (0,0), (-1,-1), 9),
        ("BOX", (0,0), (-1,-1), 0.5, BORDER),
        ("INNERGRID", (0,0), (-1,-1), 0.5, BORDER),
        ("BACKGROUND", (0,0), (-1,0), NAVY),
        ("TEXTCOLOR", (0,0), (-1,0), WHITE),
        ("TOPPADDING", (0,0), (-1,-1), 6),
        ("BOTTOMPADDING", (0,0), (-1,-1), 6),
    ]
    for i in range(1, len(table_data)):
        if i % 2 == 0:
            comp_style.append(("BACKGROUND", (0,i), (-1,i), GREY_BG))
    comp_table.setStyle(TableStyle(comp_style))
    elements.append(comp_table)
    elements.append(Spacer(1, 16))

    # ── Barzel Scores ───────────────────────────────────────────────────────
    elements.append(Paragraph(t["scoring"], styles["SectionTitle"]))

    score_header = [
        Paragraph(f'<b>{t["district"]}</b>', styles["SmallGrey"]),
        Paragraph("<b>Liquidity</b>", styles["SmallGrey"]),
        Paragraph("<b>Yield</b>", styles["SmallGrey"]),
        Paragraph("<b>Risk</b>", styles["SmallGrey"]),
        Paragraph("<b>Trend</b>", styles["SmallGrey"]),
        Paragraph(f'<b>{t["score_label"]}</b>', styles["SmallGrey"]),
        Paragraph("<b>Label</b>", styles["SmallGrey"]),
    ]
    score_data = [score_header]
    sorted_scores = sorted(dist_scores, key=lambda s: s["total"], reverse=True)
    for sc in sorted_scores:
        sc_color = _score_color(sc["total"])
        row = [
            Paragraph(f'<b>{sc["district"]}</b>', styles["BodyText2"]),
            Paragraph(f'{sc["liquidity"]:.1f}', styles["BodyText2"]),
            Paragraph(f'{sc["yield"]:.1f}', styles["BodyText2"]),
            Paragraph(f'{sc["risk"]:.1f}', styles["BodyText2"]),
            Paragraph(f'{sc["trend"]:.1f}', styles["BodyText2"]),
            Paragraph(f'<b>{sc["total"]:.1f}</b>', ParagraphStyle("sc", parent=styles["BodyText2"], textColor=sc_color, fontName="Helvetica-Bold")),
            Paragraph(sc["label"], styles["BodyText2"]),
        ]
        score_data.append(row)

    s_cols = 7
    s_w = doc.width / s_cols
    score_table = Table(score_data, colWidths=[s_w]*s_cols)
    score_style = [
        ("ALIGN", (0,0), (-1,-1), "CENTER"),
        ("ALIGN", (0,0), (0,-1), "LEFT"),
        ("VALIGN", (0,0), (-1,-1), "MIDDLE"),
        ("FONTSIZE", (0,0), (-1,-1), 9),
        ("BOX", (0,0), (-1,-1), 0.5, BORDER),
        ("INNERGRID", (0,0), (-1,-1), 0.5, BORDER),
        ("BACKGROUND", (0,0), (-1,0), NAVY),
        ("TEXTCOLOR", (0,0), (-1,0), WHITE),
        ("TOPPADDING", (0,0), (-1,-1), 6),
        ("BOTTOMPADDING", (0,0), (-1,-1), 6),
    ]
    score_table.setStyle(TableStyle(score_style))
    elements.append(score_table)
    elements.append(Spacer(1, 24))

    # ── Disclaimer ──────────────────────────────────────────────────────────
    elements.append(Paragraph(t["disclaimer"], styles["SmallGrey"]))

    # Build
    doc.build(elements)
    buffer.seek(0)

    return StreamingResponse(
        buffer,
        media_type="application/pdf",
        headers={"Content-Disposition": "attachment; filename=barzel-memo.pdf"},
    )
